name: Compilar APK Android

on: 
  push:
    branches: [ "main", "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configurar o Java (Necessário para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Removemos a etapa manual do Flutter. O Flet fará isso sozinho agora.

      - name: Instalar o Flet e Dependências
        run: pip install -r requirements.txt

      - name: Compilar o APK
        # O "yes |" aperta "y" + Enter automaticamente para a pergunta de instalação
        run: yes | flet build apk -v 

      - name: Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: BuscaPreco-Gertec-Emulador
          path: build/apk/**/*.apk
